version: '3.8'
services:
  frontend:
    build: ./client
    ports:
      - "3000:80"
    depends_on:
      - backend
    networks:
      - app-network

  backend:
    build: ./server
    ports:
      - "3001:3000"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge