export const portfolioItems = [
    {
        heading: 'Threads',
        subheading: 'Illustration',
        img: 'assets/img/portfolio/1.jpg',
        alt: 'Threads project image',
        intro: 'Lorem ipsum dolor sit amet consectetur.',
        description: 'Use this area to describe your project. Lorem ipsum dolor sit amet, consectetur adipisicing elit. Est blanditiis dolorem culpa incidunt minus dignissimos deserunt.',
        client: 'Threads',
        category: 'Illustration',
    },
    {
        heading: 'Explore',
        subheading: 'Graphic Design',
        img: 'assets/img/portfolio/2.jpg',
        alt: 'Explore project image',
        intro: 'Lorem ipsum dolor sit amet consectetur.',
        description: 'Use this area to describe your project. Lorem ipsum dolor sit amet, consectetur adipisicing elit. Est blanditiis dolorem culpa incidunt minus dignissimos deserunt.',
        client: 'Explore',
        category: 'Graphic Design',
    },
    {
        heading: 'Finish',
        subheading: 'Identity',
        img: 'assets/img/portfolio/3.jpg',
        alt: 'Finish project image',
        intro: 'Lorem ipsum dolor sit amet consectetur.',
        description: 'Use this area to describe your project. Lorem ipsum dolor sit amet, consectetur adipisicing elit. Est blanditiis dolorem culpa incidunt minus dignissimos deserunt.',
        client: 'Finish',
        category: 'Identity',
    },
    {
        heading: 'Lines',
        subheading: 'Branding',
        img: 'assets/img/portfolio/4.jpg',
        alt: 'Lines project image',
        intro: 'Lorem ipsum dolor sit amet consectetur.',
        description: 'Use this area to describe your project. Lorem ipsum dolor sit amet, consectetur adipisicing elit. Est blanditiis dolorem culpa incidunt minus dignissimos deserunt.',
        client: 'Lines',
        category: 'Branding',
    },
    {
        heading: 'Southwest',
        subheading: 'Website Design',
        img: 'assets/img/portfolio/5.jpg',
        alt: 'Southwest project image',
        intro: 'Lorem ipsum dolor sit amet consectetur.',
        description: 'Use this area to describe your project. Lorem ipsum dolor sit amet, consectetur adipisicing elit. Est blanditiis dolorem culpa incidunt minus dignissimos deserunt.',
        client: 'Southwest',
        category: 'Website Design',
    },
    {
        heading: 'Window',
        subheading: 'Photography',
        img: 'assets/img/portfolio/6.jpg',
        alt: 'Window project image',
        intro: 'Lorem ipsum dolor sit amet consectetur.',
        description: 'Use this area to describe your project. Lorem ipsum dolor sit amet, consectetur adipisicing elit. Est blanditiis dolorem culpa incidunt minus dignissimos deserunt.',
        client: 'Window',
        category: 'Photography',
    },
];